# Generated by Django 3.0.5 on 2021-03-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210305_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
