# Generated by Django 3.0.5 on 2021-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210305_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_code',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Company Code'),
        ),
    ]
