# Generated by Django 3.0.5 on 2021-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210305_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='company_code',
            new_name='company_name',
        ),
    ]
