# Generated by Django 3.0.5 on 2021-03-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210305_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company'),
        ),
        migrations.CreateModel(
            name='Subsidiaries',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Subsidiaries Code')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='subsidiary',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Subsidiaries'),
        ),
    ]
