# Generated by Django 3.0.5 on 2021-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='subsidiaries',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
